osx_image: xcode7.1
language: objective-c

xcode_project: APIBase.xcodeproj
xcode_sdk: iphonesimulator9.1
install:
- gem install cocoapods
- gem install xcpretty

script:
- xcodebuild test -project APIBase.xcodeproj -scheme 'APIBaseiOS' -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)' | xcpretty -c
- xcodebuild test -project APIBase.xcodeproj -scheme 'APIBaseOSX' -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)' | xcpretty -c
- xcodebuild -project APIBase.xcodeproj -scheme 'Podspec Lint' -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)' | xcpretty -c

env:
    global:
    - TIMEOUT=1000
    matrix:
    - USE_NETWORK=true
